name:                bloomgus
version:             0.1.0.0
github:              "gusbicalho/bloomgus"
license:             BSD3
author:              "Gustavo Bicalho"
maintainer:          "gusbicalho@gmail.com"
copyright:           "2019 Gustavo Bicalho"

extra-source-files:
- README.md
- ChangeLog.md
- src/cbits/*.c
- src/cbits/*.h

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gusbicalho/bloomgus#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- array

ghc-options:
- -O2
- -Wall
c-sources: src/cbits/*.c
cc-options: -O3
include-dirs: src/cbits
install-includes: src/cbits/lookup3.h

library:
  source-dirs: src
  exposed-modules:
  - Bloomgus.Immutable
  - Bloomgus.Mutable
  - Bloomgus.Easy
  - Bloomgus.Hash

executables:
  bloomgus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts=some
    - -with-rtsopts=-N
    dependencies:
    - bloomgus
    - unix
  profiling-exe:
    main: Words.hs
    source-dirs: profiling
    ghc-options:
    - -threaded
    - -rtsopts=all
    - -with-rtsopts=-N
    - -O2
    - -fprof-auto
    dependencies:
    - bloomgus
    - parallel
    - deepseq
    - time

tests:
  bloomgus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bloomgus
    - hspec
    - QuickCheck
